name: Deploy to S3 Based on Branch Name
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
on:
  push:
    branches:
      - '*' # Trigger on all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Sync branch content to corresponding S3 bucket
    - name: Deploy to S3
      run: |
        # Get the branch name
        BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's|refs/heads/||')

        # S3 bucket name is the same as the branch name
        BUCKET_NAME=$BRANCH_NAME

        echo "Deploying branch '$BRANCH_NAME' to S3 bucket 's3://$BUCKET_NAME'"

        # Sync all files in the branch to the corresponding S3 bucket
        aws s3 sync . s3://$BUCKET_NAME --delete
